server:
  port: 8010
lettuce:
  standalone:
    port: 6379
redisson:
  host: 127.0.0.1
  port: 6379

zoo:
  host: ubuntu.wsl
  port: 2181

# jetcache
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379